# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Customizing Blacklight
tagline:             'HydraConnect 2015'
description:         'Click the links below to see high-level pages about customizing parts of your Blacklight application.'
url:                 http://lanyon.getpoole.com
baseurl:             '/customizing-blacklight'
paginate:            5
highlighter:         pygments

# Custom vars
blacklight_version:             5.14.0
